### ISSUE TITLE
Ordenar notas desde más reciente a más vieja

### ISSUE THREAD

**Issue by GuidoDipietro** [UTN-FRBA-Mobile/Capture#11]
actualmente se ordena justamente al inverso de eso

**Comment by tomasmoreira04** [comment]
@GuidoDipietro ya tengo la solución en un branch 😛, que opinas que es mejor? Ordenar por fecha de creación o por la más recientemente actualizada?

**Comment by crisszkutnik** [comment]
Para mi por fecha de creacion porque es algo consistente, aunque creo que lo ideal seria tener un boton para cambiar entre las dos opciones
